version: '3.9'

services:
  app:
    container_name: qrsAppBff
    build: .
    # command: ./scripts/run.sh
    ports:
      - '8083:8080'
      - '9236:9229' # Debug port
    volumes:
      - ./src:/app/src
      - ./scripts:/app/scripts
    env_file:
      - .env.docker
